### ISSUE TITLE
Doesn't save last read sometimes

### ISSUE THREAD

**Issue by cpiber** [Glagan/MyMangaDex#25]
In my save export I can see that the last-property is null, but the chapter array contains the last chapter I read (it's always the only one if that changes things).

**Comment by Glagan** [comment]
What exactly is the last property (key) ? Do you have the *bigger history* option enabled ?
Do you also have the *save all opened chapters* option enabled, it's this one that save each chapters in the chapter array.  
Can I have an extract of your save that show the problem ?

**Comment by cpiber** [comment]
The property is `null`. I do not have bigger history enabled. I have save all opened chapters enabled (I think). I'll be able to clarify and send the save when I'm home in a few hours.

**Comment by cpiber** [comment]
```
  "33379": {
    "mal": 120899,
    "last": null,
    "chapters": [
      6
    ],
    "lastTitle": 1580284113579
  },
```
This is one of the entries where it happened

**Comment by Glagan** [comment]
Weird, I don't have any in my save and I can't reproduce it, did you visit only the title page for this title, or did you visit a title page and then a chapter page or just a chapter page without visiting a title page before ?

It shouldn't change anything anyway, I pushed a fix that should set the chapter to -1 in some places that I missed but I never saw something that could make it null, maybe it was related to #24.

**Comment by cpiber** [comment]
Not fixed, seems to be a problem when directly opening the chapter without ever having been on the title page.
```
  "21055": {
    "mal": 105747,
    "last": null,
    "chapters": [
      28
    ],
    "lastTitle": 1580494320060
  },
```
```
  "options": {
    "lastReadColor": "rgba(75, 180, 60, 0.6)",
    "lowerChaptersColor": "rgba(180, 102, 75, 0.4)",
    "higherChaptersColor": "transparent",
    "nextChapterColor": "rgba(199, 146, 2, 0.4)",
    "lastOpenColors": [
      "rgba(22, 65, 87, 0.8)",
      "rgba(28, 135, 141, 0.8)",
      "rgba(28, 103, 141, 0.8)"
    ],
    "openedChaptersColor": "rgba(28, 135, 141, 0.4)",
    "hideLowerChapters": false,
    "hideHigherChapters": false,
    "saveOnlyHigher": true,
    "saveOnlyNext": true,
    "confirmChapter": true,
    "saveAllOpened": true,
    "maxChapterSaved": 100,
    "updateHistoryPage": false,
    "updateOnlyInList": false,
    "historySize": 100,
    "updateMDList": true,
    "showTooltips": true,
    "showFullCover": false,
    "coverMaxHeight": 80,
    "highlightChapters": true,
    "showNotifications": true,
    "showErrors": true,
    "onlineSave": false,
    "onlineURL": "https://mmd.nikurasu.org/api/",
    "username": "",
    "isLoggedIn": false,
    "token": "",
    "version": 2.3,
    "subVersion": 16,
    "hideLastRead": false
  }
```

**Comment by cpiber** [comment]
Could the problem lie with `saveOnlyNext`? That it doesn't update `last` because it's not technically following the previous read?

**Comment by Glagan** [comment]
Sorry to respond this late.
I tried to reproduce it since you gave me some options, but I still can't reproduce it at all.
I tried with an empty default save, one with the options you gave me, visiting a chapter (the same one in your previous post) without the title page, with the title page before, by clicking refuse and accept... nothing set it to `null`.
